project_id = "outjbyzvolzffmaoczxu"

[functions.send-ticket-confirmation]
verify_jwt = true

[functions.send-winner-notification]
verify_jwt = true

[functions.send-winner-notification-admin]
verify_jwt = true

[functions.send-prize-claim-confirmation]
verify_jwt = true

[functions.check-raffle-status]
verify_jwt = false